Добавлено описание ISA стандартов в области автоматизации
idzm/Neuro-semantic-control pull request #11
Opened 2024-08-20 14:21 UTC by idzm

2024-08-21 12:07 UTC, NogameNo-life requested changes

2024-08-21 12:07 UTC, NogameNo-life commented on chapter_3.tex
>  Важную роль играют все участники процесса: пользователи - люди (операторы, мастера, начальники цеха и т.п.); устройства - датчики и исполнительные механизмы (температурные датчики, насосы, клапана и
```suggestion
Важную роль играют все участники процесса: пользователи — люди (операторы, мастера, начальники цеха и т.п.); устройства — датчики и исполнительные механизмы (температурные датчики, насосы, клапана и т.п.); механизированные системы — конвейерные системы, агрегаты; роботизированные системы — шарнирные роботы, дельта-роботы, манипуляторы; так и программные системы — SCADA, MES, ERP. Их взаимодействие обеспечивает достижение поставленной цели, устранение и предотвращение внештатных ситуаций. Причем важное влияние имеют как количественные показатели (количество операторов, устройств, агрегатов, панелей управления и т.п.), так и качество (качество устройств, квалификация операторов, качество программных систем и т.п.). В системах управления также важным является такой параметр, как скорость принятия решений — оперативное внесение изменений для выполнения поставленных планов. Онтологическое описание позволяет получить общее описание, понятное всем данным участникам процесса.
```

2024-08-22 05:04 UTC, idzm commented on chapter_3.tex
>  Важную роль играют все участники процесса: пользователи - люди (операторы, мастера, начальники цеха и т.п.); устройства - датчики и исполнительные механизмы (температурные датчики, насосы, клапана и
Вот правило (https://habr.com/ru/articles/75662/):

![изображение](https://github.com/user-attachments/assets/a728052d-3c77-48d7-b06c-e1a5a8419933)

2024-08-23 11:06 UTC, idzm commented
Вот здесь есть информация о современном использования LaTeX - https://github.com/mrkline/modern-latex.

2024-08-23 11:32 UTC, NogameNo-life approved these changes

2024-08-23 11:32 UTC, merged